### ISSUE TITLE
Create .rpm packages for gnatsd

### ISSUE THREAD

**Issue by petemiron** [nats-io/gnatsd#569] opened 2017-08-29 14:26 UTC
This feature must meet the following requirements:

- [ ] Create .rpm
- [ ] Create users and groups for running NATS.
- [ ] Starting with systemd for daemon management
- [ ] Create default, but complete, config with commented out unused config items

subset of #404

**Comment by derekcollison** [comment] 2018-08-23 23:52
Dupe of #404

**Closed by derekcollison** 2018-08-23 23:52 UTC
