### ISSUE TITLE
Please provide gnatsd DEB/RPM packages

### ISSUE THREAD

**Issue by monotek** [nats-io/gnatsd#717] opened 2018-08-03 20:30 UTC
- [ x] Feature Request or Change Proposal
 
#### OS/Container environment:
Debian / Ubuntu / Centos

## Feature Requests
Please provide gnatsd DEB & RPM packages

#### Use Case:
Running nats server in a vm or on bare metal without using a container
 
#### Proposed Change:
Create DEB / RPM repos
 
#### Who Benefits From The Change(s)?
Everybody who likes to run the server in a non containerized environement

**Comment by ripienaar** [comment] 2018-08-03 20:55
Alas a dupe of numerous others https://github.com/nats-io/gnatsd/issues/404 https://github.com/nats-io/gnatsd/issues/569 am sure there were more

I publish RPMs for streaming server fwiw but not gnatsd

**Comment by monotek** [comment] 2018-08-03 21:00
I'm currently trying to build packages for Debian 8, Debian 9, Centos 6, Centos 7, Ubuntu 16.04, Ubuntu 18.04 and SLES12 via packager.io service. I'll do a pull request as soon as its ready...

**Comment by ripienaar** [comment] 2018-08-03 21:33
Yeah sadly those come with so much extra baggage that personally I wouldn’t run them. Wouldn’t be a generic solution imo

**Comment by derekcollison** [comment] 2018-08-23 23:53
Closing and will track #404

**Closed by derekcollison** 2018-08-23 23:53 UTC
