### ISSUE TITLE
will c.pa.sid change when deliverMsg?

### ISSUE THREAD

**Issue by wustrong** [nats-io/gnatsd#244] opened 2016-04-15 07:24 UTC
### print the in come message summary in processMsgArgs(), the sid is right.
```
2016/04/15 10:13:37 |info| [["Inf|NATS|Route372d830a3c25f7fd6301928a0383f587|New message, message subject is <itxxx.alm.ccc.task.report>, sid is <QRSID:352:35658>, reply is <_INBOX.750e197327173fbd681372df490b37e5>, from <192.128.0.11:50022>."]]

2016/04/15 10:13:37 |info| [["subscriptions list of <itxxx.alm.ccc.task.report> are below:"]]
2016/04/15 10:13:37 |info| [["sub client id:<352>,  sub client type:<0>, host_port:<192.128.0.10:32431>, sub.sid:<35658>, sub.queue:<Schedule>"]]
```

### print rsid when c.type is ROUTE
```
func (s *Server) routeSidQueueSubscriber(rsid []byte) (*subscription, bool) {
	if !bytes.HasPrefix(rsid, []byte(QRSID)) {
		Log("rsid don't hava prefix QRSID in routeSidQueueSubscriber(), ", string(rsid))
		return nil, false
	}
	matches := qrsidRe.FindSubmatch(rsid)
	if matches == nil || len(matches) != EXPECTED_MATCHES {
		Log("rsid don't match qrsidRe.FindSubmatch(rsid) in routeSidQueueSubscriber(), ", string(rsid))
		return nil, false
	}
	cid := uint64(parseInt64(matches[RSID_CID_INDEX]))
	client := s.clients[cid]
	if client == nil {
		return nil, true
	}
	sid := matches[RSID_SID_INDEX]
	if sub, ok := (client.subs.Get(sid)).(*subscription); ok {
		return sub, true
	}
	return nil, true
}
```

```
2016/04/15 10:13:37 |info| [["rsid don't have prefix QRSID in routeSidQueueSubscriber(), ", "MHxDT01QTEVURQA"]]
2016/04/15 10:13:37 |info| [["return not OK in routeSidQueueSubscriber()"]]
```

### the rsid has changed, then message lost.

p.s.  
`2016/04/15 10:13:37 |info| [["Message's length is longer than client.bw.Available:<32768> < <36884>"]] `
### message is long, but deliver correctly,  may not the reason change c.pa.sid value.

**Comment by derekcollison** [comment] 2016-04-15 08:49
So is the issue you observed message loss that you are trying to figure out how it happened? 

It sounds like you have a cluster of servers, can you send us the configurations for those and how to reproduce (the test) the message loss?

Thanks

**Comment by wustrong** [comment] 2016-04-15 12:17
our 
`name: gnatsd
net:"192.128.0.11"
port: 50021

pid_file: "/home/itpaas/nats/bin/nats.pid"

log_file: "/home/itpaas/logs/itpaas/nats/nats.log"
debug: false
trace: false
authorization {
  timeout: 45
}

cluster {
  host:"192.128.0.11"
  port: 50022

  authorization {
    timeout: 45
  }

  routes = [
    "nats-route://192.128.0.12:50022"
    "nats-route://192.128.0.10:50022"

  ]
}
http_port: 50020
#max size for each log file(>=10), unit is MB. default value is 10.
logmaxsize: 20
#max count of log files(>=10). default value is 10.
#logmaxcount: 10
`
we hava 3 VMs, which installed 3 services, and lots of clients in the 3 VMs to send many many messages. some messages's size may be bigger than default buffer size.

**Comment by derekcollison** [comment] 2016-04-15 13:08
Do you have messages that are over 1MB big?

**Comment by derekcollison** [comment] 2016-04-15 13:09
Which client libraries are you using?

**Comment by kozlovic** [comment] 2016-04-15 13:48
More questions. In the first excerpt, it looks like the subject is missing, is it that you forgot to print it?
```
2016/04/15 10:13:37 |info| [["Inf|NATS|Route372d830a3c25f7fd6301928a0383f587|New message, message subject is , sid is QRSID:352:35658, reply is <_INBOX.750e197327173fbd681372df490b37e5>, from 192.128.0.11:50022."]]
```

What version of gnastd are you using? Is it a release build (which one)? If not, what's the last commit to use this as a reference point when checking the code?

Thanks!

**Comment by wustrong** [comment] 2016-04-16 02:23
@derekcollison 
1、we have messages that are over 1MB.
2、we use 3rd party java client [https://github.com/cloudfoundry-community/java-nats/](url)

@kozlovic 
1、I hava printed it， it lost when I copy here.  

> [["Inf|NATS|Route372d830a3c25f7fd6301928a0383f587|New message, message subject is \<itpaas.alm.ccc.task.report\>, sid is <QRSID:352:35658>, reply is <_INBOX.52d2ce190eb51887ea7e3703afe9975>, from <192.128.0.11:50022>."]]


2、gnatsd version:`[["Starting gnatsd version 0.5.2"]]`

Thanks!

**Comment by kozlovic** [comment] 2016-04-16 02:36
Ok, so I think you are hitting the defect fixed by https://github.com/nats-io/gnatsd/commit/1b39a9fe94fdc44b6bb91bc2975242d27bcd7577. Unfortunately for you, this was ported down to 0.6.0 but not before that.

Note that most of Apcera supported client now check for the server message limit, which by default is 1MB and will fail to send. Otherwise, the server will drop messages above 1MB.

I would recommend that you upgrade your server, also be aware of the 1MB payload size limitation (unless you modify and recompile the server, the limit applies).

**Comment by kozlovic** [comment] 2016-04-16 02:51
Note that enforcing a payload limit of 1MB was introduce in 0.6.2 as far as I can tell. Again, if you upgrade and this limit is too low, you can increase with config file parameter `max_payload`. As an example, check `server/configs/test.conf` (or alternatively build from source with setting a higher limit).

**Comment by wustrong** [comment] 2016-04-16 03:09
Thanks you very much! @derekcollison @kozlovic 
Sorry for that I can't find the answer in issues.

**Comment by kozlovic** [comment] 2016-04-18 16:40
@wustrong No problem! I am going to close this issue, let us know if upgrading does not solve your issue.

**Closed by kozlovic** 2016-04-18 16:40 UTC
